### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by zhangfq-chemistry** [rail5/bashpp#1]
g++ -O2 -s -o bpp main.cpp -std=gnu++20
main.cpp:11:10: fatal error: token.cpp: No such file or directory
   11 | #include "token.cpp"

**Comment by rail5** [comment]
The Bash++ compiler is not written yet; it's not expected to compile. A 'release' will be made once we have a functional version of the compiler

**Comment by rail5** [comment]
A beta version of the Bash++ has now been released. It should compile just fine now
